BOXTOP.SHOP/BoxTop/BoxTop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoxTop.Data;
using BoxTop.Models;

namespace BoxTop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly DatabaseContext _context;

        public ProductsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ProductCategory,ProductName,Cost,CountInBase,Description,ImageUrl")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ProductCategory,ProductName,Cost,CountInBase,Description,ImageUrl")] Product product)
        {
            if (id != product.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ID == id);
        }
    }
}

BOXTOP.SHOP/BoxTop/BoxTop/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoxTop.Data;
using BoxTop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using BoxTop.Functions;
using BoxTop.ProviderJWT;

namespace BoxTop.Controllers
{
    public class UsersController : Controller
    {
        private readonly DatabaseContext _context;

        public UsersController(DatabaseContext context)
        {
            _context = context;
        }



        //_____________________________________________________________________________________________________________________


        // GET: Users/Authorisation
        [Route("Authorisation")]
        public async Task<IActionResult> Authorisation()
        {
            return View();
        }

        [Route("Authorisation")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Authoristation([Bind("Login, Password")] User realUser)
        {
            User userTruly = _context.Users.Where(s => s.Login == realUser.Login && s.Password == Hasher.GetHashString(realUser.Password)).FirstOrDefault<User>();
            if (userTruly == null)
            {
                return View("Error");
            }
            else
            {
                var token = new JwtTokenBuilder()
                                .AddSecurityKey(JWTSecurityKey.Create("Test-secret-key-1234"))
                                .AddSubject(userTruly.Login)
                                .AddIssuer("Test.Security.Bearer")
                                .AddAudience("Test.Security.Bearer")
                                .AddClaim(userTruly.Role, userTruly.ID.ToString())
                                .AddExpiry(200)
                                .Build();
                userTruly.LastToken = token.Value;

                //Обновляем данные в БД по пользователю
                _context.Users.Update(userTruly);
                _context.SaveChanges();

                if (realUser != null)
                {
                    HttpContext.Session.SetString("Token", userTruly.LastToken);
                    HttpContext.Session.SetString("Login", userTruly.Login);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("Error");
                }
            }
        }

        // GET: Users/LogOut
        [Route("LogOut")]
        public async Task<IActionResult> LogOut()
        {
            string user = HttpContext.Session.GetString("Login");
            user = user != null ? user : "";
            HttpContext.Session.SetString("Token", "");
            HttpContext.Session.SetString("Login", "");
            return RedirectToAction("Index", "Home");
        }

        //________________________________________________________________________________________________________________________

        // GET: Users
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> GetUsers()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        //ДОЛЖНО БЫТЬ ВИДНО САМОМУ 5 ПОЛЬЗОВАТЕЛЮ И АДМИНУ
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Login,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Role = "User";
                user.Password = Hasher.GetHashString(user.Password);
                _context.Add(user);
                await _context.SaveChangesAsync();

                //ЗАПИСЬ ТОКЕНА В СЕССИЮ, СОЗДАНИЕ ТОКЕНА


                return RedirectToAction("Index", "Home");
            }

            //
            return View(user);
        }

        // GET: Users/Edit/5
        //Должно быть доступно только для самого пользователя, админа
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        //Должно быть доступно только для самого пользователя, админа
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Login,Password,Role,LastToken")] User user)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    user.Password = Hasher.GetHashString(user.Password);
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index","Home");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        //Должно быть доступно только для самого пользователя, админа
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        //Должно быть доступно только для самого пользователя, админа
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.ID == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.ID == id);
        }
    }
}

BOXTOP.SHOP/BoxTop/BoxTop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gift Top</title>
    <style>
        .pointer {
            cursor: pointer
        }
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="" class="navbar-brand">Gift Top</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Подарочная коробка<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Products" asp-action="Index" asp-route-id="1">Products</a></li>
                        </ul>
                    </li>
                </ul>
                @{
                    var token = new Byte[500];
                    Context.Session.TryGetValue("Token", out token);
                    var login = new Byte[500];
                    Context.Session.TryGetValue("Login", out login);
                    string tokenString = "";
                    string tokenStringJS = "test";
                    if (login == null || (login != null && System.Text.Encoding.Default.GetString(login) == ""))
                    {
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script>
                            $(document).ready(function () {
                                $('#submitButton').click(function () {
                                    alert("you must be authorized!");
                                });
                                $('#submitButton2').click(function () {
                                    alert("you must be authorized!");
                                });
                            });
                        </script>
                    }
                    if (token != null && System.Text.Encoding.Default.GetString(token) != "")
                    {
                        tokenStringJS = System.Text.Encoding.Default.GetString(token);
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
                        <script>
                var tkn = "@tokenStringJS";
                var link = "@BoxTop.Links.Self";
                            //_________________________________________________________________
                            $(document).ready(function () {
                                $('#submitButton').click(function () {
                                    $.ajax({
                                        url: link+"/allitems",
                                        type: 'GET',
                                        contentType: 'application/json',
                                        headers: {
                                            "Authorization": "Bearer " + tkn
                                        },
                                        async: false,
                                        success: function (html) {
                                            $(window.document.body).html(html);
                                        }
                                    });
                                });
                            });
                        </script>
                        @if (System.Text.Encoding.Default.GetString(login) == "Vova")
                        {
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a id="submitButton" class="pointer">All Items</a></li>
                                        <li><a asp-area="" asp-controller="Home" asp-action="GetUsers" asp-route-id="1">All Users</a></li>
                                        <li><a asp-area="" asp-controller="Home" asp-action="GetOrders" asp-route-id="1">All Orders</a></li>
                                    </ul>
                                </li>
                            </ul>
                        }

                        tokenString = System.Text.Encoding.Default.GetString(token);
                    }

                    if (tokenString == "")
                    {
                        tokenString = "false";
                        <ul class="nav navbar-nav navbar-right">
                            <li><a asp-area="" asp-controller="Users" asp-action="Create">Registration</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="Authorisation">Authorisation</a></li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            @{
                                if (token != null && System.Text.Encoding.Default.GetString(token) != "")
                                {
                                    string loginString = System.Text.Encoding.Default.GetString(login);
                                }
                            }
                            <li><a asp-area="">Hello, @System.Text.Encoding.Default.GetString(login)</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="LogOut">Log Out</a></li>
                        </ul>
                    }
                }
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - AggregationService</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>